#!/usr/bin/env bash
# Dependencies: amixer, siji

# tries to get the master mixer
mixer=$(amixer sget Master)

if [[ $mixer != "" ]]; then
	volume=$( echo $mixer | sed -n "0,/.*\[\([0-9]\+\)%\].*/s//\1/p")
	state=$( echo $mixer | grep -Eoe '\[(on|off)\]')
else
	# gets the default mixer if it fails to get the master
	volume=$( amixer -D default | sed -n "0,/.*\[\([0-9]\+\)%\].*/s//\1/p")
	state=$( amixer -D default | grep -Eoe '\[(on|off)\]')
fi

if   [[ $volume -eq 0 || $state == '[off]' ]]; then
    token=''
elif [[ $volume -gt 50 ]]; then
    token=''
else
    token=''
fi

echo "$token $volume%"
