#!/usr/bin/env bash
# Dependencies: amixer, siji

# gets the master mixer
# sometimes the card which contains the mixer may not come first so you have to iterate
mixer=""
card_no=0
while [[ $mixer == "" ]]; do
	mixer=$(amixer -c ${count} sget Master)
	volume=$( echo $mixer | sed -n "0,/.*\[\([0-9]\+\)%\].*/s//\1/p")
	state=$( echo $mixer | grep -Eoe '\[(on|off)\]')
	((card_no++))
done

if   [[ $volume -eq 0 || $state == '[off]' ]]; then
    token=''
elif [[ $volume -gt 50 ]]; then
    token=''
else
    token=''
fi

echo "$token $volume%"
