#!/bin/env bash
#  Author: Mirko van der Waal
#  Mail: <mvdw at airmail dot cc>
#  Distributed under terms of the GNU2 license.
#
#  The MIT License (MIT)
#
#  Copyright (c) 2015 A[muse]ment
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

set -e

if [[ ! -d ~/.config/captain ]]; then
    mkdir -p ~/.config/captain
fi && exec 3<> ~/.config/captain/captain.log

cd $(dirname $0)

source <(python3 -c "
import sys, re, configparser
c = configparser.ConfigParser()
c.read(sys.argv[1])
for section in c:
    for key in c[section]:
        current = re.sub('[\n ]', '$', c[section][key]).split('$')
        key = key.replace('-', '_')
        if len(current) == 1: print(\"{}_{}={}\".format(section, key, current[0]))
        else: print(\"{}_{}=({})\".format(section, key, \" \".join(current)))
" captainrc 2>&3) 2>&3

trap "rm -f \"$unique\" \"$process\"; trap - TERM; kill 0" INT ERR TERM QUIT EXIT

export process=/tmp/captain-process
export unique=/tmp/captain-stack

# Does this need revision? Yes.
stack() {
    # Manage various stacks of unique characters which are to be attached later.
    {
        if [[ ${#@} -ge 1 ]]; then
            case $1 in
                construct)
                    for section in captain.d/*; do
                        printf "%s" "$(basename $section):" {A..E} $'\n' >> $unique
                    done
                    ;;
                retrieve)
                    IFS=":"
                    stack_t=($(grep -e "$2:" < <(cat $unique)))
                    sed -i "/$2:/d" $unique
                    echo ${stack_t[1]:0:1}
                    echo "${stack_t[0]}:${stack_t[1]:1:$((${#stack_t[1]} + 1))}" >> $unique
                    ;;
                *)
                    echo "Stack: Invalid argument."
                    exit 0
                    ;;
            esac
        else
            echo "Stack: You did not specify enough arguments."
            exit 0
        fi
    } 2>&3
} && export -f stack

stack construct

# Does this need revision? No.
handle() {
    {
    # Catch string from stdout and execute the matching commands.
    while read -r line; do
        local cmd=${handle[$line]}
        if [[ ! -z $cmd ]]; then
            echo "$cmd &"
        fi
    done
    } 2>&3
}

# Does this need revision? No.
format() {
    {
    # Dynamically format all the available options and display them accordingly.
    position=$(sed 's/|/%{r}/' <(sed 's/|/%{c}/' <<< $bar_position))
    position=$(sed 's/:/ /g' <<< $position)
    for script in captain.d/*; do
        position=$(sed "s/$(basename $script)/\$__$(basename $script)/g" <<< $position)
        switch="$switch $(basename $script)) __$(basename $script)=\${line#*@} ;;"
    done
    echo $switch
    while read -r line; do
        eval "case ${line%%@*} in
            $switch
        esac"
        eval "echo \"$position\""
    done
    } 2>&3
}

# Does this need revision? Likely.
{
    # Bar related things.
    declare -A bar
    bar=([background]="#FFFFFFFF"
         [background]="#FF000000"
         [position]="||"
         [offset]=0
         [height]=20
         [fonts]="monospace-9"
         [dock]="top")
    for section in "${!bar[@]}"; do
        if [[ $(eval "echo \${#bar_${section}}") -eq 0 ]]; then
            echo "Main: No value for 'bar-$section' -> using ${bar[${section}]}"
            eval "bar_${section}=${bar[${section}]}"
        fi
    done
    bar_fonts=$(printf " -f %s" "${bar_fonts[@]}")
    [[ $bar_offset -gt 0 ]] && bar_offset="-o $bar_offset" || bar_offset=""
    [[ $bar_dock == "bottom" ]] && bar_dock="-b" || bar_dock=""
    if [[ ! -z `pgrep bspwm` ]]; then
        bspc config top_padding $bar_height
    fi
} 2>&3

# Does this need revision? No.
{
    # Set the a default choice for every variable that is not defined.
    declare -A choices
    choices=([foreground]="#FFFFFFFF"
             [background]="#FF000000"
             [underline]=false
             [overline]=false
             [display]=false
             [reload]=5)
    for file in captain.d/*; do
        name=$(basename $file)
        for section in "${!choices[@]}"; do
            if [[ $(eval "echo \${#${name}_${section}}") -eq 0 ]]; then
                echo "Main: No value for '${name}-$section' -> using ${choices[${section}]}"
                eval "${name}_${section}=${choices[${section}]}"
            fi
        done
    done
} 2>&3

# Does this need revision? Likely.
{
    # Create 'event' and 'over- underline' handles that are embedded when parsing
    # the output string.
    declare -A handle area
    for file in captain.d/*; do
        name=$(basename $file)
        events=("mouse_middle" "scroll_down" "mouse_right" "mouse_left" "scroll_up")
        area["${name}_p"]="%{"
        area["${name}_s"]="%{"
        for decoration in overline underline; do
            if [[ $(eval "echo \${${name}_$decoration}") = true ]]; then
                area["${name}_p"]="${area["${name}_p"]}+${decoration:0:1}"
                area["${name}_s"]="${area["${name}_s"]}-${decoration:0:1}"
            fi
        done
        area["${name}_p"]="${area["${name}_p"]}}"
        area["${name}_s"]="${area["${name}_s"]}}"
        for event in ${events[@]}; do
            if [[ ! -z $(eval "echo \${${name}_${event}}") ]]; then
                uid="$(stack retrieve ${name})${name}"
                handle[${uid}]="$(eval "echo \${${name}_${event}}")"
                case "$event" in
                    "mouse_middle") event=2 ;;
                    "scroll_down") event=5 ;;
                    "mouse_right") event=3 ;;
                    "mouse_left") event=1 ;;
                    "scroll_up") event=4 ;;
                esac
                area["${name}_p"]="${area["${name}_p"]}%{A${event}:${uid}:}"
                area["${name}_s"]="${area["${name}_s"]}%{A}"
            else
                echo "Main: No events specified for '${name}-${event/_/-}' -> using none."
            fi
        done
    done
} 2>&3

# Does this need revision? No.
{
    # Parse our previously collected elements to a full string.
    if [[ -e $process ]]; then
        rm $process
    fi && mkfifo "$process"
    for file in captain.d/*; do
        name=$(basename $file)
        if [[ $(eval "echo \${${name}_display}") = true ]]; then
            while :; do
                printf "%s" \
                    "${name}@" \
                    "$(eval "echo \${area[${name}_p]"})" \
                    "%{$(eval "echo \${area[${name}_d]"})}" \
                    "%{F$(eval "echo \${${name}_foreground}")}" \
                    "%{B$(eval "echo \${${name}_background"})}" \
                    "$(tr '\n' ' ' < <(bash < "$file"))" \
                    "%{F-}%{B-}" \
                    "$(eval "echo \${area[${name}_s]"})" \
                    $'\n'
                sleep $(eval "echo \${${name}_reload"})
            done > "$process" &
        else
            echo "Main: ${name} is set not to display."
        fi
    done
    echo
} 2>&3

cat "$process" | format | lemonbar $bar_dock $bar_offset $bar_fonts -g x$bar_height -F "$bar_foreground" -B "$bar_background" | handle | sh
wait
